### PR TITLE
examples: Add gradient operators and new features for C stiffness matrix 

### PR DESCRIPTION
**Pull request by guaacoelho**

### CODE REVIEW

**Review by AtilaSaraiva — APPROVED** [review]
LGTM

**Comment by AtilaSaraiva** [comment]
actually, can you change the name of the PR
stiffness sound weird.

**Comment by nogueirapeterson** [comment]
> actually, can you change the name of the PR stiffness sound weird.

Done!

**Review by nogueirapeterson — APPROVED** [review]

**Comment by AtilaSaraiva** [comment]
@guaacoelho can you fix the problems Peterson notified. Please use git blame to check which commits were responsible for the lines and edit them, don't create new commits.

**Pull request merged**
